sudo: true
language: node_js
node_js:
  - "stable"
  - "5"
  - "5.1"
  - "4"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
before_install:
  - npm install -g mocha
  - npm install -g coveralls
  - npm install -g istanbul
install:
  - npm install
after_success:
  - if [[ `node --version` == *v0.12* ]]; then cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi
