p = require('path')
fs = require('fs')
zlib = require('zlib')
uglifyjs = require('uglify-js')
etag = require('etag')
sourceInfo = require(p.resolve(__dirname, './sourceInfo.js'))
module.exports = ((fileName) ->
  object = sourceInfo(fileName)
  buffer = fs.readFileSync(fileName)
  minimizedBuffer = new Buffer(uglifyjs.minify(buffer.toString('utf8'),
    mangle: false
    fromString: true).code, 'utf8')
  minimizedMangledBuffer = new Buffer(uglifyjs.minify(buffer.toString('utf8'),
    mangle: true
    fromString: true).code, 'utf8')
  bestBuffer = zlib.gzipSync(minimizedMangledBuffer, level: zlib.Z_BEST_COMPRESSION)
  object.MINIMIZED_SIZE = minimizedBuffer.length
  object.MINIMIZED_MANGLED_SIZE = minimizedMangledBuffer.length
  object.BEST_SIZE = bestBuffer.length
  object
)(__filename)

# ---
# generated by js2coffee 2.1.0